### ISSUE TITLE
Cannot digest images. Too many connection errors, etc. Memory Leak? 

### ISSUE THREAD

**Issue by micheal-cooper** [ywc/ywc#27]
TIDA becomes unable to digest images for announcements, word of mouth, marketplace.

Catalina tells me that 
"NFO: Maximum number of threads (200) created for connector with address null and port 8080"

I reboot apache and then tomcat and get:

Recoverable error on line 21 of ywc-intranet-directory.xsl:
  FODC0002: Document has been marked not available: file:/opt/ywc/cache/xml/cache/aaaaaz.xml
Error on line 252 column 1 of aaaaaz.xml:
  SXXP0003: Error reported by XML parser: XML document sJun 12, 2014 10:20:57 AM org.apache.coyote.http11.Http11Protocol pause
INFO: Pausing Coyote HTTP/1.1 on http-8080
Jun 12, 2014 10:20:58 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: A web application appears to have started a thread named [Connect thread media.oist.jp session] but has failed to stop it. This is very likely to create a memory leak.
…

NFO: Deploying configuration descriptor manager.xml
Jun 12, 2014 10:21:02 AM org.apache.catalina.session.StandardManager doLoad
SEVERE: IOException while loading persisted sessions: java.io.EOFException
java.io.EOFException
     at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2323)
     at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2792)
     at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:800)
     at java.io.ObjectInputStream.<init>(ObjectInputStream.java:298)
     at org.apache.catalina.util.CustomObjectInputStream.<init>(CustomObjectInputStream.java:58)
     at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:362)
     at org.apache.catalina.session.StandardManager.load(StandardManager.java:321)
     at org.apache.catalina.session.StandardManager.start(StandardManager.java:637)
     at org.apache.catalina.core.ContainerBase.setManager(ContainerBase.java:438)
     at org.apache.catalina.core.StandardContext.start(StandardContext.java:4396)
     at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
     at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
     at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:526)
     at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:637)
     at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:563)
     at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:498)
     at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1277)
     at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:321)
     at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
     at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
     at org.apache.catalina.core.StandardHost.start(StandardHost.java:722)
     at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
     at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:443)
     at org.apache.catalina.core.StandardService.start(StandardService.java:516)
     at org.apache.catalina.core.StandardServer.start(StandardServer.java:710)
     at org.apache.catalina.startup.Catalina.start(Catalina.java:593)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:622)
     at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
     at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
Jun 12, 2014 10:21:02 AM org.apache.catalina.session.StandardManager start
SEVERE: Exception loading sessions from persistent storage
…

Jun 12, 2014 10:21:02 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 766 ms
Jun 12, 2014 10:21:13 AM org.apache.tomcat.util.net.JIoEndpoint createWorkerThread
INFO: Maximum number of threads (200) created for connector with address null and port 8080
id: rsbpndonqfswdxofrgnyqcazoqtyoocv
creating working copies
-> png: success 332
-> jpg: success 191
single frame
creating thumbnails
-> jpg: success 164ms
-> png: success 169ms
publishing working copies
-> jpg: success 20683ms
-> png delete: success 1ms
publishing thumbnails
-> jpg: success 25874ms
-> png: success 17133ms

This looks relevant:
http://serverfault.com/questions/340360/memory-leak-in-tomcat

Looking at httpd logs, it seems that the number of connections needed by Tomcat is overwhelming httpd:

[root@tidafe2 log]#tail -f /var/log/httpd/error_log
[Thu Jun 12 10:20:36 2014] [notice] caught SIGTERM, shutting down
[Thu Jun 12 10:20:47 2014] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu Jun 12 10:20:47 2014] [notice] mod_webauth: initialized (4.1.0)
[Thu Jun 12 10:20:47 2014] [warn] module webauth_module is already loaded, skipping
[Thu Jun 12 10:20:47 2014] [warn] module ssl_module is already loaded, skipping
[Thu Jun 12 10:20:47 2014] [notice] Digest: generating secret for digest authentication ...
[Thu Jun 12 10:20:47 2014] [notice] Digest: done
[Thu Jun 12 10:20:47 2014] [notice] mod_webauth: initialized (4.1.0)
[Thu Jun 12 10:20:47 2014] [notice] Apache/2.2.15 (Unix) DAV/2 mod_auth_kerb/5.4 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips WebAuth/4.1.0 configured -- resuming normal operations
[Thu Jun 12 10:24:25 2014] [error] server reached MaxClients setting, consider raising the MaxClients setting

I will try rebooting the server.

Then I will try raising MaxClients settings, but restarting both httpd and tomcat did not fix it, so I am not sure what will.

![screen shot 2014-06-12 at 10 35 25](https://cloud.githubusercontent.com/assets/3095809/3253207/aedd1cbc-f1d2-11e3-9403-d66177627143.jpg)
![screen shot 2014-06-12 at 10 35 16](https://cloud.githubusercontent.com/assets/3095809/3253208/aedd2428-f1d2-11e3-865d-a3e3d8b4468e.jpg)

**Comment by micheal-cooper** [comment]
Looks like the disk was full again. The httpd logs fill up /var really quickly.

IT will send me an early warning at 90% usage to give us a better heads-up in the future.

I am closing this.
